<?php


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'IAD',
  'author' => 'IAD BreadCrumb by www.sugar-project.com',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'IAD BreadCrumb by www.sugar-project.com',
  'published_date' => '2015-07-30 13:17:49',
  'type' => 'module',
  'version' => 1027,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'BreadCrumb',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'IAD_BreadCrumb',
      'class' => 'IAD_BreadCrumb',
      'path' => 'modules/IAD_BreadCrumb/IAD_BreadCrumb.php',
      'tab' => false,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
   ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/IAD_BreadCrumb',
      'to' => 'modules/IAD_BreadCrumb',
    ),
    1 => 
    array(
      'from' => '<basepath>/logic_hook/IAD_BreadCrumb_logic_hook.php',
      'to' => 'custom/modules/IAD_BreadCrumb_logic_hook.php',
    ),
    2 => 
      array (
            'from' => '<basepath>/SugarModules/modules/Administration/IAD_BreadCrumb_settings.php',
            'to' => 'modules/Administration/IAD_BreadCrumb_settings.php',
       ),  
    3 => 
      array (
            'from' => '<basepath>/themes/SuiteR',
            'to' => 'themes/SuiteR',
       ),  
    4 => 
      array (
            'from' => '<basepath>/custom/Extension/application/Ext/Language/en_us.IAD_BreadCrumb.php',
            'to' => 'custom/Extension/application/Ext/Language/en_us.IAD_BreadCrumb.php',
      )                                    
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 =>
    array(
          'from'=> '<basepath>/language/administration.en_us.php',
          'to_module'=> 'Administration',
          'language'=>'en_us'
        ), 
  ),
'logic_hooks' => array(
    // global logic hook
    array( 
      'module' => '',
      'hook' => 'after_ui_frame',
      'order' => 60,
      'description' => 'link to IAD_BreadCrumb.js',
      'file' => 'custom/modules/IAD_BreadCrumb_logic_hook.php',
      'class' => 'IAD_BreadCrumb_logic_hook',
      'function' => 'IAD_BreadCrumb_logic_hook',
    ),                                       
  ),
  'administration'=> array(
        array(
            'from'=>'<basepath>/administration/IAD_BreadCrumb_settings.php',
        ),
    ),  
);