<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'porq',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Purchase_Request',
  'published_date' => '2016-04-09 17:48:38',
  'type' => 'module',
  'version' => 1460224118,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Purchase_Request',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'porq_Purchase_Request',
      'class' => 'porq_Purchase_Request',
      'path' => 'modules/porq_Purchase_Request/porq_Purchase_Request.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'porq_Purchase_Request_Lines',
      'class' => 'porq_Purchase_Request_Lines',
      'path' => 'modules/porq_Purchase_Request_Lines/porq_Purchase_Request_Lines.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/porq_po_request_appr_approvals_porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/porq_purchase_request_porq_purchase_request_lines_porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/porq_po_request_appr_approvalsMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/porq_purchase_request_porq_purchase_request_linesMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/porq_Purchase_Request',
      'to' => 'modules/porq_Purchase_Request',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/porq_Purchase_Request_Lines',
      'to' => 'modules/porq_Purchase_Request_Lines',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/appr_Approvals.php',
      'to_module' => 'appr_Approvals',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/appr_Approvals.php',
      'to_module' => 'appr_Approvals',
      'language' => 'es_es',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/appr_Approvals.php',
      'to_module' => 'appr_Approvals',
      'language' => 'ru_ru',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/appr_Approvals.php',
      'to_module' => 'appr_Approvals',
      'language' => 'de_DE',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/appr_Approvals.php',
      'to_module' => 'appr_Approvals',
      'language' => 'fr_FR',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/appr_Approvals.php',
      'to_module' => 'appr_Approvals',
      'language' => 'pt_BR',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/appr_Approvals.php',
      'to_module' => 'appr_Approvals',
      'language' => 'it_IT',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/appr_Approvals.php',
      'to_module' => 'appr_Approvals',
      'language' => 'nl_NL',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/appr_Approvals.php',
      'to_module' => 'appr_Approvals',
      'language' => 'da_DK',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/appr_Approvals.php',
      'to_module' => 'appr_Approvals',
      'language' => 'id_ID',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/appr_Approvals.php',
      'to_module' => 'appr_Approvals',
      'language' => 'hu_HU',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/appr_Approvals.php',
      'to_module' => 'appr_Approvals',
      'language' => 'pl_PL',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/appr_Approvals.php',
      'to_module' => 'appr_Approvals',
      'language' => 'tr_TR',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/appr_Approvals.php',
      'to_module' => 'appr_Approvals',
      'language' => 'es_ES',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'en_us',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'es_es',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'ru_ru',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'de_DE',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'fr_FR',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'pt_BR',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'it_IT',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'nl_NL',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'da_DK',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'id_ID',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'hu_HU',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'pl_PL',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'tr_TR',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'es_ES',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request_Lines.php',
      'to_module' => 'porq_Purchase_Request_Lines',
      'language' => 'en_us',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request_Lines.php',
      'to_module' => 'porq_Purchase_Request_Lines',
      'language' => 'es_es',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request_Lines.php',
      'to_module' => 'porq_Purchase_Request_Lines',
      'language' => 'ru_ru',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request_Lines.php',
      'to_module' => 'porq_Purchase_Request_Lines',
      'language' => 'de_DE',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request_Lines.php',
      'to_module' => 'porq_Purchase_Request_Lines',
      'language' => 'fr_FR',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request_Lines.php',
      'to_module' => 'porq_Purchase_Request_Lines',
      'language' => 'pt_BR',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request_Lines.php',
      'to_module' => 'porq_Purchase_Request_Lines',
      'language' => 'it_IT',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request_Lines.php',
      'to_module' => 'porq_Purchase_Request_Lines',
      'language' => 'nl_NL',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request_Lines.php',
      'to_module' => 'porq_Purchase_Request_Lines',
      'language' => 'da_DK',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request_Lines.php',
      'to_module' => 'porq_Purchase_Request_Lines',
      'language' => 'id_ID',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request_Lines.php',
      'to_module' => 'porq_Purchase_Request_Lines',
      'language' => 'hu_HU',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request_Lines.php',
      'to_module' => 'porq_Purchase_Request_Lines',
      'language' => 'pl_PL',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request_Lines.php',
      'to_module' => 'porq_Purchase_Request_Lines',
      'language' => 'tr_TR',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request_Lines.php',
      'to_module' => 'porq_Purchase_Request_Lines',
      'language' => 'es_ES',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'en_us',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'es_es',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'ru_ru',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'de_DE',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'fr_FR',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'pt_BR',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'it_IT',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'nl_NL',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'da_DK',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'id_ID',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'hu_HU',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'pl_PL',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'tr_TR',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
      'language' => 'es_ES',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/porq_po_request_appr_approvals_appr_Approvals.php',
      'to_module' => 'appr_Approvals',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/porq_po_request_appr_approvals_porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/porq_purchase_request_porq_purchase_request_lines_porq_Purchase_Request_Lines.php',
      'to_module' => 'porq_Purchase_Request_Lines',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/porq_purchase_request_porq_purchase_request_lines_porq_Purchase_Request.php',
      'to_module' => 'porq_Purchase_Request',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
        'appr_Approvals' => 'porq_po_request_appr_approvals_name',
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);